name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
      - name: Setup Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 #v7.1.2
      - name: Install dependencies
        run: uv sync
      - name: Lint with Ruff
        run: |
          uv run ruff check .
        continue-on-error: true
      - name: Run pre-commit checks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd #v3.0.1
      - name: Test with pytest
        run: |
          uv run coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          uv run coverage report -m
